// This file is no longer needed as robots.txt generation is handled by next-sitemap.
// Please delete this file after applying the changes.
// You can add a `export default function robots() { return { rules: [], sitemap: '' }; }` if your build process requires it,
// but `next-sitemap` will generate the actual robots.txt in the public directory.
import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  // console.warn("[robots.ts] This file is deprecated. robots.txt is generated by next-sitemap.");
  return {
    rules: [],
    sitemap: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://wallpix.vercel.app'}/sitemap.xml`,
  };
}
