// This file is no longer needed as sitemap generation is handled by next-sitemap.
// Please delete this file after applying the changes.
// You can add a `export default function sitemap() { return []; }` if your build process requires it,
// but `next-sitemap` will generate the actual sitemap.xml in the public directory.

export default function sitemap() {
  // console.warn("[sitemap.ts] This file is deprecated. Sitemap is generated by next-sitemap.");
  return [];
}
